Bag of Word : it collect all uniqe word in list from all document and give frequency of word in list
Count Vectorization  : Find each word occurence in document and convert to vector form
TF-Idf : Term frequency if occurence of word in single document Idf =log(total number of document / number of document containing a word)
it show importance of word in document

In [16]:
import numpy as np 
import pandas as pd 
import nltk 
from nltk import word_tokenize 
from collections import Counter

In [34]:
review_1="The movie was good and we really like it"
review_2="The movie was good but the ending was boring"
review_3="we did not like the movie as it was too lenghty"
review_4="I would love to see a different set of actor in the movie.A Diaster!"

1. Bag of Word

In [ ]:
nltk.download("all")

In [21]:
review_1token=word_tokenize(review_1)
review_2token=word_tokenize(review_2)
review_3token=word_tokenize(review_3)
review_4token=word_tokenize(review_4)

In [22]:
review_token=set(review_1token).union(set(review_2token)).union(set(review_3)).union(review_4)

In [23]:
len(review_token)

39

In [24]:
review1_dict=Counter(review_1token)
review1_dict

Counter({'The': 1,
         'movie': 1,
         'was': 1,
         'good': 1,
         'and': 1,
         'we': 1,
         'really': 1,
         'like': 1,
         'it': 1})

In [25]:
review2_dict=Counter(review_2token)
review3_dict=Counter(review_3token)
review4_dict=Counter(review_4token)

In [26]:
review_dict_df=pd.DataFrame([review1_dict,review2_dict,review3_dict,review4_dict])

In [33]:
review_dict_df=review_dict_df.fillna(0)
review_dict_df

,The,movie,was,good,and,we,really,like,it,but,...,see,a,different,set,of,actor,in,movie.A,Diaster,!
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

2. Count Vectorizer

In [47]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [43]:
countvect=CountVectorizer()

In [44]:
reviewlist=[review_1,review_2,review_3,review_4]
X_counts=countvect.fit_transform(reviewlist)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 39 stored elements and shape (4, 27)>

In [45]:
X_name=countvect.get_feature_names_out()
X_name

array(['actor', 'and', 'as', 'boring', 'but', 'diaster', 'did',
       'different', 'ending', 'good', 'in', 'it', 'lenghty', 'like',
       'love', 'movie', 'not', 'of', 'really', 'see', 'set', 'the', 'to',
       'too', 'was', 'we', 'would'], dtype=object)

In [46]:
cv=pd.DataFrame(X_counts.toarray(),columns=X_name)
cv

,actor,and,as,boring,but,diaster,did,different,ending,good,...,of,really,see,set,the,to,too,was,we,would
0,0,1,0,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,1,0
1,0,0,0,1,1,0,0,0,1,1,...,0,0,0,0,2,0,0,2,0,0
2,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,1,1,1,0
3,1,0,0,0,0,1,0,1,0,0,...,1,0,1,1,1,1,0,0,0,1

In [49]:
tfid=TfidfVectorizer(min_df=1,lowercase=True,stop_words='english',)
tf_Count=tfid.fit_transform(reviewlist)
tf_Count

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 18 stored elements and shape (4, 13)>

In [50]:
tfdf=pd.DataFrame(tf_Count.toarray(),columns=tfid.get_feature_names_out())
tfdf

,actor,boring,diaster,did,different,ending,good,lenghty,like,love,movie,really,set
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.497096,0.000000,0.497096,0.000000,0.329023,0.630504,0.000000
1,0.000000,0.587838,0.000000,0.000000,0.000000,0.587838,0.463458,0.000000,0.000000,0.000000,0.306758,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.587838,0.000000,0.000000,0.000000,0.587838,0.463458,0.000000,0.306758,0.000000,0.000000
3,0.435511,0.000000,0.435511,0.000000,0.435511,0.000000,0.000000,0.000000,0.000000,0.435511,0.227268,0.000000,0.435511