Finding the root of word is called lemmetization, it give single word
Finding the verb form is called stemming

In [1]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
import re

In [2]:
gold = """Gold is a chemical element with symbol Au (from Latin: aurum) and atomic number 79, making it one of the higher atomic number elements that occur naturally. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal. Chemically, gold is a transition metal and a group 11 element. It is one of the least reactive chemical elements and is solid under standard conditions. Gold often occurs in free elemental (native) form, as nuggets or grains, in rocks, in veins, and in alluvial deposits. It occurs in a solid solution series with the native element silver (as electrum) and also naturally alloyed with copper and palladium. Less commonly, it occurs in minerals as gold compounds, often with tellurium (gold tellurides).

Gold is resistant to most acids, though it does dissolve in aqua regia, a mixture of nitric acid and hydrochloric acid, which forms a soluble tetrachloroaurate anion. Gold is insoluble in nitric acid, which dissolves silver and base metals, a property that has long been used to refine gold and to confirm the presence of gold in metallic objects, giving rise to the term acid test. Gold also dissolves in alkaline solutions of cyanide, which are used in mining and electroplating. Gold dissolves in mercury, forming amalgam alloys, but this is not a chemical reaction.

A relatively rare element,[5][6] gold is a precious metal that has been used for coinage, jewelry, and other arts throughout recorded history. In the past, a gold standard was often implemented as a monetary policy, but gold coins ceased to be minted as a circulating currency in the 1930s, and the world gold standard was abandoned for a fiat currency system after 1971.

A total of 186,700 tonnes of gold exists above ground, as of 2015.[7] The world consumption of new gold produced is about 50% in jewelry, 40% in investments, and 10% in industry.[8] Gold's high malleability, ductility, resistance to corrosion and most other chemical reactions, and conductivity of electricity have led to its continued use in corrosion resistant electrical connectors in all types of computerized devices (its chief industrial use). Gold is also used in infrared shielding, colored-glass production, gold leafing, and tooth restoration. Certain gold salts are still used as anti-inflammatories in medicine. As of 2016, the world's largest gold producer by far was China with 450 tonnes per year"""

In [3]:
token=word_tokenize(gold,preserve_line=True)

In [4]:
from nltk.stem import PorterStemmer,LancasterStemmer,SnowballStemmer

In [5]:
pst=PorterStemmer()

In [6]:
words=['give','given','giving','gave']

In [7]:
for word in words: 
    print(f'word : {word}  PorterStemmer : {pst.stem(word)}')

word : give  PorterStemmer : give
word : given  PorterStemmer : given
word : giving  PorterStemmer : give
word : gave  PorterStemmer : gave

In [8]:
LcSt=LancasterStemmer()

In [9]:
for word in words: 
    print(f'word : {word}  LanchterStemmer : {LcSt.stem(word)}')

word : give  LanchterStemmer : giv
word : given  LanchterStemmer : giv
word : giving  LanchterStemmer : giv
word : gave  LanchterStemmer : gav

In [10]:
snoSt=SnowballStemmer('english')

In [11]:
for word in words: 
    print(f'word : {word}  SnowballStemmer : {snoSt.stem(word)}')

word : give  SnowballStemmer : give
word : given  SnowballStemmer : given
word : giving  SnowballStemmer : give
word : gave  SnowballStemmer : gave

In [12]:
from nltk.stem import wordnet
from nltk.stem import WordNetLemmatizer

In [13]:
lmtz=WordNetLemmatizer()

In [14]:
lmtz.lemmatize('corpora')

'corpus'

In [15]:
for word in words: 
    print(f'word : {word}  Lemmatize : {lmtz.lemmatize(word,pos='n')}')

word : give  Lemmatize : give
word : given  Lemmatize : given
word : giving  Lemmatize : giving
word : gave  Lemmatize : gave

In [16]:
wrdlst=['gone','going','went']
for word in wrdlst: 
    print(f'word : {word}  Lemmatize : {lmtz.lemmatize(word, pos='v')}')

word : gone  Lemmatize : go
word : going  Lemmatize : go
word : went  Lemmatize : go

In [17]:
from nltk.corpus import stopwords
import re

In [18]:
stpwords=stopwords.words('english')
print(stpwords)
print(stpwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [19]:
punctuation=re.compile(r'[-?!,:;()|0-9]',re.UNICODE)

In [20]:
punt=[]
for word in token:
    puntword=punctuation.sub('',word)
    if len(puntword)>0: 
        punt.append(puntword)

In [21]:
len(punt)

401

In [22]:
punt2=[]
for word in punt:
    word=word.lower()
    if word not in stpwords: 
        punt2.append(word)

In [23]:
len(punt2)

247

In [24]:
frq=FreqDist(punt2)

In [25]:
frq

FreqDist({'gold': 22, 'used': 5, 'chemical': 4, '.': 4, 'acid': 4, '[': 4, ']': 4, 'element': 3, 'standard': 3, 'often': 3, ...})

In [26]:
frq.most_common(10)

[('gold', 22),
 ('used', 5),
 ('chemical', 4),
 ('.', 4),
 ('acid', 4),
 ('[', 4),
 (']', 4),
 ('element', 3),
 ('standard', 3),
 ('often', 3)]

In [27]:
import docx

In [28]:
doc=docx.Document("Data/Brexit.docx")

In [34]:
full_txt = []
for para in doc.paragraphs:
    if para.text.strip():
        full_txt.append(para.text)

text = " ".join(full_txt)   # convert list → string
text = ' '.join(text.split())
#clean_text = text.replace('\xa0', ' ')
print(text)

Brexit is the impending withdrawal of the United Kingdom (UK) from the European Union (EU). In a referendum on 23 June 2016, a majority of British voters supported leaving the EU. On 29 March 2017, the UK government invoked Article 50 of the Treaty on European Union. The European Union (Withdrawal) Act 2018 declares "exit day" to be 29 March 2019 at 11 p.m. (Central European Time). Prime Minister Theresa May announced the government's intention not to seek permanent membership of the European single market or the EU customs union after leaving the EU and promised to repeal the European Communities Act of 1972 and incorporate existing European Union law into UK domestic law. A new government department, the Department for Exiting the European Union, was created in July 2016. Negotiations with the EU officially started in June 2017, aiming to complete the withdrawal agreement by October 2018. In June 2018, the UK and the EU published a joint progress report outlining agreement on issues including customs, VAT and Euratom. The UK joined the European Communities (EC) in 1973, with membership confirmed by a referendum in 1975. In the 1970s and 1980s, withdrawal from the EC was advocated mainly by Labour Party members and trade union figures. From the 1990s, the main advocates of withdrawal were the newly founded UK Independence Party (UKIP) and an increasing number of Eurosceptic Conservative Party members. Prime Minister David Cameron held the referendum in fulfilment of a 2015 manifesto pledge. Cameron, who had campaigned for "Remain", resigned after the referendum result and was succeeded by Theresa May, who called a snap general election less than a year later, in which she lost her overall majority. Her minority government is supported in key votes by the Democratic Unionist Party. Six weeks after the referendum, the Bank of England introduced quantitative easing and lower interest rates, thus allowing both depreciation of sterling and a rise in inflation that outpaced wage growth for most of 2017. The drop in the value of sterling has been claimed to have been caused in part by hedge-fund managers betting on Brexit against polls predicting a narrow victory for the "Remain" camp. There is a broad consensus in existing economic research that Brexit is likely to reduce the UK's real per capita income in the medium term and long term. There is also agreement among economists that the Brexit referendum itself damaged the economy in the subsequent two years. Studies on effects that have materialised since the referendum show annual losses of £404 for the average UK household, and losses between 1.3% and 2.1% of UK GDP. Brexit is likely to reduce immigration from European Economic Area (EEA) countries to the UK, and poses challenges for UK higher education and academic research. As of June 2018, the size of the "divorce bill", the UK's inheritance of existing EU trade agreements, and relations with Ireland and other EU member states remain uncertain. The precise impact on the UK depends on whether the process will be a "hard" or a "soft" Brexit.

In [ ]:
!pip install spacy

In [ ]:
!python -m spacy download en_core_web_sm

In [37]:
import en_core_web_sm
npl = en_core_web_sm.load()

In [38]:
import pandas as pd
import spacy

In [39]:
#nlp=spacy.load('en_core_web_sm') for co llab
posdata=[]
doc1=npl(text)
for word in doc1: 
    posdata.append({
        'Token' : word.text,
        'Lemma' : word.lemma_,
        'Pos'   : word.pos_,
        'Tag'   : word.tag_, 
        'Dependency' : word.dep_
    })
df=pd.DataFrame(posdata)
df

          Token       Lemma    Pos  Tag Dependency
0        Brexit      Brexit  PROPN  NNP      nsubj
1            is          be    AUX  VBZ       ROOT
2           the         the    DET   DT        det
3     impending   impending    ADJ   JJ       amod
4    withdrawal  withdrawal   NOUN   NN       attr
..          ...         ...    ...  ...        ...
581           "           "  PUNCT   ``      punct
582        soft        soft    ADJ   JJ       amod
583           "           "  PUNCT   ''      punct
584      Brexit      Brexit  PROPN  NNP       conj
585           .           .  PUNCT    .      punct

[586 rows x 5 columns]

In [41]:
enn_Data=[]
for ent in doc1.ents: 
    enn_Data.append({
        'Entity':ent.text,
        'Type':ent.label_, 
        'Label':ent.label,
        'start char': ent.start_char, 
        'end char'  :  ent.end_char
    })

In [44]:
entdf=pd.DataFrame(enn_Data)

In [45]:
entdf

                Entity    Type  Label  start char  end char
0               Brexit  PERSON    380           0         6
1   the United Kingdom     GPE    384          38        56
2                   UK     GPE    384          58        60
3   the European Union     ORG    383          67        85
4                   EU     ORG    383          87        89
..                 ...     ...    ...         ...       ...
75                  EU     ORG    383        2906      2908
76             Ireland     GPE    384        2946      2953
77                  EU     ORG    383        2964      2966
78                  UK     GPE    384        3025      3027
79              Brexit  PERSON    380        3088      3094

[80 rows x 5 columns]

In [46]:
from spacy import displacy

In [48]:
ner_html=displacy.render(doc1,style='ent',page=True)
ner_html

In [53]:
sentence=list(doc1.sents)
sentence

[Brexit is the impending withdrawal of the United Kingdom (UK) from the European Union (EU).,
 In a referendum on 23 June 2016, a majority of British voters supported leaving the EU.,
 On 29 March 2017, the UK government invoked Article 50 of the Treaty on European Union.,
 The European Union (Withdrawal) Act 2018 declares "exit day" to be 29 March 2019 at 11 p.m. (Central European Time).,
 Prime Minister Theresa May announced the government's intention not to seek permanent membership of the European single market or the EU customs union after leaving the EU and promised to repeal the European Communities Act of 1972 and incorporate existing European Union law into UK domestic law.,
 A new government department, the Department for Exiting the European Union, was created in July 2016.,
 Negotiations with the EU officially started in June 2017, aiming to complete the withdrawal agreement by October 2018.,
 In June 2018, the UK and the EU published a joint progress report outlining agreement on issues including customs, VAT and Euratom.,
 The UK joined the European Communities (EC) in 1973, with membership confirmed by a referendum in 1975.,
 In the 1970s and 1980s, withdrawal from the EC was advocated mainly by Labour Party members and trade union figures.,
 From the 1990s, the main advocates of withdrawal were the newly founded UK Independence Party (UKIP) and an increasing number of Eurosceptic Conservative Party members.,
 Prime Minister David Cameron held the referendum in fulfilment of a 2015 manifesto pledge.,
 Cameron, who had campaigned for "Remain", resigned after the referendum result and was succeeded by Theresa May, who called a snap general election less than a year later, in which she lost her overall majority.,
 Her minority government is supported in key votes by the Democratic Unionist Party.,
 Six weeks after the referendum, the Bank of England introduced quantitative easing and lower interest rates, thus allowing both depreciation of sterling and a rise in inflation that outpaced wage growth for most of 2017.,
 The drop in the value of sterling has been claimed to have been caused in part by hedge-fund managers betting on Brexit against polls predicting a narrow victory for the "Remain" camp.,
 There is a broad consensus in existing economic research that Brexit is likely to reduce the UK's real per capita income in the medium term and long term.,
 There is also agreement among economists that the Brexit referendum itself damaged the economy in the subsequent two years.,
 Studies on effects that have materialised since the referendum show annual losses of £404 for the average UK household, and losses between 1.3% and 2.1% of UK GDP.,
 Brexit is likely to reduce immigration from European Economic Area (EEA) countries to the UK, and poses challenges for UK higher education and academic research.,
 As of June 2018, the size of the "divorce bill", the UK's inheritance of existing EU trade agreements, and relations with Ireland and other EU member states remain uncertain.,
 The precise impact on the UK depends on whether the process will be a "hard" or a "soft" Brexit.]

In [55]:
dep_html=displacy.render(sentence,style='dep',page=True)
dep_html